### ISSUE TITLE
This is my code for the submission I was trying to create a filter pipeline for the search but was un able to get it to work please take a look.

### ISSUE THREAD

**Issue by farmerj50** [angular-react-learning/employee-management#2]
[employee-management (2).zip](https://github.com/angular-react-learning/employee-management/files/4393535/employee-management.2.zip)

**Comment by angular-react-learning** [comment]
`import { Pipe, PipeTransform } from '@angular/core';
@Pipe({
  name: 'filter'
})
export class FilterPipe implements PipeTransform {
  transform(items: any[], searchText: string): any[] {

    console.log(items, searchText)

    if (!items) return [];
    if (!searchText) return items;
    searchText = searchText.toLowerCase();
    return items.filter(it => {
      return it.username.toLowerCase().indexOf(searchText) > -1;
    });
  }
}`

**Comment by angular-react-learning** [comment]
`<div class="employee-list">
    <ul>
        <li *ngFor="let employee of employees | filter : searchtext">
            <a routerLink="/employee/{{employee.username}}">{{employee.username}}</a>
        </li>
    </ul>
</div>

<input [(ngModel)] = "searchtext" type="text"/>
`

**Comment by angular-react-learning** [comment]
[employee-management.zip](https://github.com/angular-react-learning/employee-management/files/4394850/employee-management.zip)

**Comment by angular-react-learning** [comment]
Fixed,].
